url: https://y7kim.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: FISH-quant
email: your-email@domain.com
description: "Analyze smFISH images with Python and ImJoy."


# Team names, titles and social links
people:
- name: Arthur IMBERT
  pic: arthur-imbert
  position: Lead Developer
  social:
    - title: github
      url: https://github.com/Henley13
    - title: linkedin
      url: https://www.linkedin.com/in/arthur-imbert-b6887683/

- name: Florian MUELLER
  pic: florian-mueller
  position: Project supervision, Developer
  social:
    - title: github
      url: https://github.com/muellerflorian
    - title: linkedin
      url: https://www.linkedin.com/in/muellerflorian/

- name: Thomas WALTER
  pic: thomas-walter
  position: Project supervision, Developer
  social:
    - title: github
      url: https://github.com/ThomasWalter
    - title: linkedin
      url: https://www.linkedin.com/in/thomaswalter4/

- name: Wei OUYANG
  pic: wei-ouyang
  position: Developer
  social:
    - title: github
      url: https://github.com/oeway
    - title: linkedin
      url: https://www.linkedin.com/in/weiouyang/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:

  - title: github
    url: https://github.com/fish-quant

# Postal address (add as many lines as necessary)
address:
  - line: https://github.com/fish-quant

# Build settings
markdown: kramdown
permalink: pretty